### PR TITLE
help flag + helptext (needs to be updated)

### PR DESCRIPTION
**Pull request by thepigeonoftime**
helptext in help.js is a placeholder from current ooniprobe and needs to be updated

### CODE REVIEW

**Comment by hellais** [comment]
Thanks for this, I will check it out!

**Comment by thepigeonoftime** [comment]
helptext for unavailable nettests is largely a placeholder and should be improved

**Comment by hellais** [comment]
I am checking out this branch.

@p1g30n be careful that your editor adds extra whitespace at the end of lines:

screen shot 2017-10-19 at 12 00 38

**Comment by hellais** [comment]
I made some changes on top of your branch and merged it into master, namely:

* I sketched out the top level help file
* Refactored help function into `cli/output` modules
* Injected the header properly into every help output
* Made some changes to how help is being handled for subcommands

**Comment by thepigeonoftime** [comment]
@hellais Thanks for the heads up, had reinstalled, just fixed my settings. 
Changes look good, the only thing I've just noticed is that nettest subcommands are case-sensitive, maybe it makes sense to normalise them for more convenient usage.

**Pull request merged**
